config/routes.rb
Rails.application.routes.draw do
  resources :customers, except: [:edit, :update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "customers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :email,
    presence: { message: "E-Mail darf nicht leer sein" },
    email: { message: "Dies ist keine gültige E-Mail-Adresse" },
    uniqueness: { case_sensitive: false, message: "Diese E-Mail-Adresse wird bereits verwendet" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ edit destroy ]

  def index
    @customers = Customer.all.reverse
    redirect_to new_customer_path unless @customers.any?
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        success_msg = "Kunde wurde erfolgreich erstellt."
        format.turbo_stream do 
          flash.now[:success] = success_msg
          render turbo_stream:
            [
              turbo_stream.prepend('customers', partial: 'customer', locals: { customer: @customer }),
              turbo_stream.update('new_customer', partial: 'new_customer_link'),
              turbo_stream.update('flash-messages', partial: 'partials/flash')
            ]
        end
        format.html { redirect_to customers_path, notice: success_msg }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @customer.destroy!

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Kunde wurde erfolgreich gelöscht." }
    end
  end

  private
  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>" class="shadow-md md:shadow-none gap-2 rounded flex flex-col md:flex-row items-center py-2 px-4">
  <p class="basis-1/3">
  <span class="font-bold md:hidden">Vorname: </span>
  <%= customer.first_name.presence || 'N/A' %>
  </p>

  <p class="basis-1/3">
  <span class="font-bold md:hidden">Nachname: </span>
  <%= customer.last_name.presence || 'N/A' %>
  </p>

  <p class="basis-1/3">
  <span class="font-bold md:hidden">Email: </span>
  <%= customer.email %>
  </p>

  <p class="basis-1/3">
    <%= customer.created_at.strftime("%d.%m.%Y") %>
  </p>

  <%= button_to customer_path(customer), method: :delete, class: "rounded-lg inline-block hover:opacity-50 p-1", data: { turbo_confirm: "Sind Sie sicher, dass Sie diesen Kunden löschen möchten?" } do %>
    <%= inline_svg_tag "icons/delete.svg", class: "w-4 h-4" %>
  <% end %>
</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer, class: "border shadow-xl py-3 px-6 rounded") do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3 flex items-center gap-4">
      <%= inline_svg_tag "icons/error.svg", class: "w-10 h-10" %>
      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex gap-2">
  <div class="my-5">
    <%= form.label :first_name,  "Vorname" %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_name, "Nachname" %>
    <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email, "E-mail" %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  </div>

  <div>
    <%= form.submit "+ Kunde hinzufügen", class: "rounded-lg py-3 px-5 bg-blue-600 text-white mx-auto block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/customers/_new_customer_link.html.erb
<%= link_to "+ New Kunde", new_customer_path, class: "my-8 w-fit rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"  %>

app/views/customers/index.html.erb
<div class="w-full lg:w-2/3 mx-auto">
  <div class="flex flex-col md:flex-row gap-4 justify-between items-center">
    <h1 class="font-bold text-4xl">Kundendatenbank</h1>
    <% link_to "New Kunde", new_customer_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"  %>
  </div>

  <%= turbo_frame_tag "new_customer" do %>
    <%= render 'new_customer_link' %>
  <% end %>

  <div class="flex justify-between items-center my-8">
    <div class="min-w-full flex flex-col gap-14 md:gap-2 shadow-md rounded">
      <div class="hidden md:flex gap-2 items-center shadow bg-slate-100 py-2 px-4 rounded-sm"> 
        <p class="basis-1/3">
          <strong class="block font-medium ">Vorname:</strong>
        </p>
        <p class="basis-1/3">
          <strong class="block font-medium ">Nachname:</strong>
        </p>
        <p class="basis-1/3">
          <strong class="block font-medium ">E-mail:</strong>
        </p>
        <p class="basis-1/3">
          <strong class="block font-medium ">Erstellt:</strong>
        </p>
      </div>

      <div id="customers">
        <%= render @customers %>
      </div>
    </div>
    
  </div>

app/views/customers/new.html.erb
<div class="mx-auto md:w-1/3 w-full">
  <h1 class="font-bold text-4xl">Neu Kunde</h1>
  <%= turbo_frame_tag "new_customer" do %>
    <%= render "form", customer: @customer %>
  <% end %>

  <%= link_to "Back to customers", customers_path, class: "m-width-1/2 rounded-lg py-3 px-5 bg-purple-100 text-center block font-medium hover:opacity-80 mt-6 md:mt-12" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kunden</title>
    <meta name="viewport" content="width=device-width,initial-scale=2">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="min-h-screen flex flex-col">
    <%= render 'partials/flash' %>
    <main class="container mx-auto mt-7 md:mt-28 px-8 sm:px-12 lg:px-28 flex">
      <%= yield %>
    </main>
    <footer class="mt-auto px-11 py-4 bg-orange-200  flex flex-col md:flex-row justify-center items-center gap-8 bg-gradient-to-br from-indigo-300 to-purple-400">
      <%= link_to "https://github.com/divagueame/kunden", class:"bg-white py0 px-8 rounded flex shadow gap-8 items-center bg-opacity-80 hover:bg-opacity-100" do %>
        Martin Arce 2024
        <%= inline_svg_tag "icons/github.svg", class: "w-5 h-6" %>
      <% end %>
    </footer>
  </body>
</html>

app/views/partials/_flash.html.erb
<div id="flash-messages" class="py-1 w-full lg:w-2/3 mx-auto flex justify-center">
<% flash.each do |type, message| %>
  <div class="absolute left-1/2 -translate-x-1/2 py-4 px-3 bg-green-100 mb-5 text-green-500 font-medium rounded-lg text-center alert-<%= type %>">
    <%= message %>
  </div>
<% end %>
</div>